name: Resume Generation and Optimization Pipeline

on:
  schedule:
    - cron: '0 8 * * *'  # This runs at midnight PST (8 AM UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run data cleanup
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
      run: python scripts/data_cleanup.py
    
    - name: Generate optimized resumes
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python scripts/data_generate_resume.py
    
    - name: Upload to MongoDB
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
        MONGO_COLLECTION_NAME: ${{ secrets.MONGO_COLLECTION_NAME }}
      run: python scripts/data_upload.py
    
    - name: Fine-tune model
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
        MONGO_COLLECTION_EDITED_NAME: ${{ secrets.MONGO_COLLECTION_EDITED_NAME }}
      run: python scripts/fine_tuning.py